### ISSUE TITLE
Bluemix CLI has broken link

### ISSUE THREAD

**Issue by dionj** [IBM/serverless-home-automation#10]
I tried to access into Bluemix CLI link https://console.bluemix.net/docs/cli/reference/bluemix_cli/index.html#getting-started,  I got this error:

"Sorry, this content isn’t available.
It seems we can’t find what you’re looking for. Try the IBM Cloud Docs search to find information.
Or, go to Getting help to find out how to look for answers and ask questions through forums."

I believe it just needs some update for the broken link with IBM latest change from Bluemix to IBM Cloud

**Comment by kkbankol-ibm** [comment]
I've just updated the link, thank you for pointing that out!
